apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        tier: {{ .Values.service.tier }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SERVER_CONTEXT_PATH
          value: "/{{ .Chart.Name }}"
        - name: SPRING_PROFILES_ACTIVE
          value: {{ .Release.Namespace | upper }}
        - name: SPRING_CLOUD_CONFIG_URI
          value: "{{ .Values.configServer.protocol }}://{{ .Values.configServer.fqdn }}{{ .Values.configServer.path }}"
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}

