export const STATECHOICES = [
    "Alaska",
    "Alabama",
    "Arkansas",
    "American Samoa",
    "Arizona",
    "California",
    "Colorado",
    "Connecticut",
    "District of Columbia",
    "Delaware",
    "Florida",
    "Georgia",
    "Guam",
    "Hawaii",
    "Iowa",
    "Idaho",
    "Illinois",
    "Indiana",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Massachusetts",
    "Maryland",
    "Maine",
    "Michigan",
    "Minnesota",
    "Missouri",
    "Mississippi",
    "Montana",
    "North Carolina",
    " North Dakota",
    "Nebraska",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "Nevada",
    "New York",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Puerto Rico",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Virginia",
    "Virgin Islands",
    "Vermont",
    "Washington",
    "Wisconsin",
    "West Virginia",
    "Wyoming"
];

export const GENDERCHOICES = ['Male', 'Female', 'I prefer not to answer',];

export const RACECHOICES = [
    'White',
    'Black or African American', 
    'American Indian or Alaska Native', 
    'Native Hawaiian or other Pacific Islander', 
    'Asian', 
    'I prefer not to answer'
];
export const LANGUAGEPREFERENCECHOICES = ['English', 'Spanish'];

export const ETHNICITYCHOICES = ['Hispanic or Latino', 'Not Hispanic or Latino', 'I prefer not to answer'];

export const EDUCATIONLEVELCHOICES = [
    'Completed 1st Grade', 
    'Completed 2nd Grade', 
    'Completed 3rd Grade', 
    'Completed 4th Grade', 
    'Completed 5th Grade', 
    'Completed 6th Grade', 
    'Completed 7th Grade', 
    'Completed 8th Grade', 
    'Completed 9th Grade', 
    'Completed 10th Grade', 
    'Completed 11th Grade', 
    'High School Degree', 
    'GED or High School Equivalency Diploma',
    'Some Vocational or Technical School (No Certificate)',
    'Some College (No Degree)',
    'Associate\'s Degree',
    'Bachelor\'s Degree',
    'Master\'s Degree',
    'Doctoral Degree',
    'Post-Doctorate Studies'
];