---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: {{.Values.service.protocol }}
    targetPort: {{ .Values.service.internalPort }}
    name: {{ .Values.service.name }}
  selector:
    app: {{ template "name" . }}
    tier: {{ .Values.service.tier }}
